// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OfferingInitParameters struct {

	// The number of CPU cores.
	// Changing this forces a new resource to be created.
	// Number of CPU cores
	CPUNumber *float64 `json:"cpuNumber,omitempty" tf:"cpu_number,omitempty"`

	// The speed of the CPU in Mhz.
	// Changing this forces a new resource to be created.
	// Speed of CPU in Mhz
	CPUSpeed *float64 `json:"cpuSpeed,omitempty" tf:"cpu_speed,omitempty"`

	// The display text of the service offering.
	DisplayText *string `json:"displayText,omitempty" tf:"display_text,omitempty"`

	// The host tags for the service offering.
	// The host tag for this service offering
	HostTags *string `json:"hostTags,omitempty" tf:"host_tags,omitempty"`

	// Restrict the CPU usage to committed service offering.
	// Changing this forces a new resource to be created.
	// Restrict the CPU usage to committed service offering
	LimitCPUUse *bool `json:"limitCpuUse,omitempty" tf:"limit_cpu_use,omitempty"`

	// Memory reserved by the VM in MB.
	// Changing this forces a new resource to be created.
	// The total memory of the service offering in MB
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// Name of the service offering.
	// Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The HA for the service offering.
	// Changing this forces a new resource to be created.
	// The HA for the service offering
	OfferHa *bool `json:"offerHa,omitempty" tf:"offer_ha,omitempty"`

	// The storage type of the service offering. Values are local and shared.
	// Changing this forces a new resource to be created.
	// The storage type of the service offering. Values are local and shared
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

type OfferingObservation struct {

	// The number of CPU cores.
	// Changing this forces a new resource to be created.
	// Number of CPU cores
	CPUNumber *float64 `json:"cpuNumber,omitempty" tf:"cpu_number,omitempty"`

	// The speed of the CPU in Mhz.
	// Changing this forces a new resource to be created.
	// Speed of CPU in Mhz
	CPUSpeed *float64 `json:"cpuSpeed,omitempty" tf:"cpu_speed,omitempty"`

	// The display text of the service offering.
	DisplayText *string `json:"displayText,omitempty" tf:"display_text,omitempty"`

	// The host tags for the service offering.
	// The host tag for this service offering
	HostTags *string `json:"hostTags,omitempty" tf:"host_tags,omitempty"`

	// The ID of the service offering.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Restrict the CPU usage to committed service offering.
	// Changing this forces a new resource to be created.
	// Restrict the CPU usage to committed service offering
	LimitCPUUse *bool `json:"limitCpuUse,omitempty" tf:"limit_cpu_use,omitempty"`

	// Memory reserved by the VM in MB.
	// Changing this forces a new resource to be created.
	// The total memory of the service offering in MB
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// Name of the service offering.
	// Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The HA for the service offering.
	// Changing this forces a new resource to be created.
	// The HA for the service offering
	OfferHa *bool `json:"offerHa,omitempty" tf:"offer_ha,omitempty"`

	// The storage type of the service offering. Values are local and shared.
	// Changing this forces a new resource to be created.
	// The storage type of the service offering. Values are local and shared
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

type OfferingParameters struct {

	// The number of CPU cores.
	// Changing this forces a new resource to be created.
	// Number of CPU cores
	// +kubebuilder:validation:Optional
	CPUNumber *float64 `json:"cpuNumber,omitempty" tf:"cpu_number,omitempty"`

	// The speed of the CPU in Mhz.
	// Changing this forces a new resource to be created.
	// Speed of CPU in Mhz
	// +kubebuilder:validation:Optional
	CPUSpeed *float64 `json:"cpuSpeed,omitempty" tf:"cpu_speed,omitempty"`

	// The display text of the service offering.
	// +kubebuilder:validation:Optional
	DisplayText *string `json:"displayText,omitempty" tf:"display_text,omitempty"`

	// The host tags for the service offering.
	// The host tag for this service offering
	// +kubebuilder:validation:Optional
	HostTags *string `json:"hostTags,omitempty" tf:"host_tags,omitempty"`

	// Restrict the CPU usage to committed service offering.
	// Changing this forces a new resource to be created.
	// Restrict the CPU usage to committed service offering
	// +kubebuilder:validation:Optional
	LimitCPUUse *bool `json:"limitCpuUse,omitempty" tf:"limit_cpu_use,omitempty"`

	// Memory reserved by the VM in MB.
	// Changing this forces a new resource to be created.
	// The total memory of the service offering in MB
	// +kubebuilder:validation:Optional
	Memory *float64 `json:"memory,omitempty" tf:"memory,omitempty"`

	// Name of the service offering.
	// Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The HA for the service offering.
	// Changing this forces a new resource to be created.
	// The HA for the service offering
	// +kubebuilder:validation:Optional
	OfferHa *bool `json:"offerHa,omitempty" tf:"offer_ha,omitempty"`

	// The storage type of the service offering. Values are local and shared.
	// Changing this forces a new resource to be created.
	// The storage type of the service offering. Values are local and shared
	// +kubebuilder:validation:Optional
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

// OfferingSpec defines the desired state of Offering
type OfferingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OfferingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OfferingInitParameters `json:"initProvider,omitempty"`
}

// OfferingStatus defines the observed state of Offering.
type OfferingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OfferingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Offering is the Schema for the Offerings API. Creates a Service Offering
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudstack}
type Offering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayText) || (has(self.initProvider) && has(self.initProvider.displayText))",message="spec.forProvider.displayText is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OfferingSpec   `json:"spec"`
	Status OfferingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OfferingList contains a list of Offerings
type OfferingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Offering `json:"items"`
}

// Repository type metadata.
var (
	Offering_Kind             = "Offering"
	Offering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Offering_Kind}.String()
	Offering_KindAPIVersion   = Offering_Kind + "." + CRDGroupVersion.String()
	Offering_GroupVersionKind = CRDGroupVersion.WithKind(Offering_Kind)
)

func init() {
	SchemeBuilder.Register(&Offering{}, &OfferingList{})
}
