// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OfferingInitParameters struct {

	// The size of the disk offering in GB.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// The display text of the disk offering.
	DisplayText *string `json:"displayText,omitempty" tf:"display_text,omitempty"`

	// The name of the disk offering.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OfferingObservation struct {

	// The size of the disk offering in GB.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// The display text of the disk offering.
	DisplayText *string `json:"displayText,omitempty" tf:"display_text,omitempty"`

	// The ID of the disk offering.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the disk offering.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OfferingParameters struct {

	// The size of the disk offering in GB.
	// +kubebuilder:validation:Optional
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// The display text of the disk offering.
	// +kubebuilder:validation:Optional
	DisplayText *string `json:"displayText,omitempty" tf:"display_text,omitempty"`

	// The name of the disk offering.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OfferingSpec defines the desired state of Offering
type OfferingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OfferingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OfferingInitParameters `json:"initProvider,omitempty"`
}

// OfferingStatus defines the observed state of Offering.
type OfferingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OfferingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Offering is the Schema for the Offerings API. Creates a Disk Offering
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudstack}
type Offering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.diskSize) || (has(self.initProvider) && has(self.initProvider.diskSize))",message="spec.forProvider.diskSize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayText) || (has(self.initProvider) && has(self.initProvider.displayText))",message="spec.forProvider.displayText is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OfferingSpec   `json:"spec"`
	Status OfferingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OfferingList contains a list of Offerings
type OfferingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Offering `json:"items"`
}

// Repository type metadata.
var (
	Offering_Kind             = "Offering"
	Offering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Offering_Kind}.String()
	Offering_KindAPIVersion   = Offering_Kind + "." + CRDGroupVersion.String()
	Offering_GroupVersionKind = CRDGroupVersion.WithKind(Offering_Kind)
)

func init() {
	SchemeBuilder.Register(&Offering{}, &OfferingList{})
}
