apiVersion: network.cloudstack.terasky.com/v1alpha1
kind: Offering
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/offering
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayText: Example Network Offering
    guestIpType: Shared
    name: example-network-offering
    trafficType: Guest
