// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NATInitParameters struct {

	// The public IP address ID for which static
	// NAT will be enabled. Changing this forces a new resource to be created.
	IPAddressID *string `json:"ipAddressId,omitempty" tf:"ip_address_id,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The virtual machine IP address to forward the
	// static NAT traffic to (useful when the virtual machine has secondary
	// NICs or IP addresses). Changing this forces a new resource to be created.
	VMGuestIP *string `json:"vmGuestIp,omitempty" tf:"vm_guest_ip,omitempty"`

	// The virtual machine ID to enable the
	// static NAT feature for. Changing this forces a new resource to be created.
	VirtualMachineID *string `json:"virtualMachineId,omitempty" tf:"virtual_machine_id,omitempty"`
}

type NATObservation struct {

	// The static nat ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The public IP address ID for which static
	// NAT will be enabled. Changing this forces a new resource to be created.
	IPAddressID *string `json:"ipAddressId,omitempty" tf:"ip_address_id,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The virtual machine IP address to forward the
	// static NAT traffic to (useful when the virtual machine has secondary
	// NICs or IP addresses). Changing this forces a new resource to be created.
	VMGuestIP *string `json:"vmGuestIp,omitempty" tf:"vm_guest_ip,omitempty"`

	// The virtual machine ID to enable the
	// static NAT feature for. Changing this forces a new resource to be created.
	VirtualMachineID *string `json:"virtualMachineId,omitempty" tf:"virtual_machine_id,omitempty"`
}

type NATParameters struct {

	// The public IP address ID for which static
	// NAT will be enabled. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	IPAddressID *string `json:"ipAddressId,omitempty" tf:"ip_address_id,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The virtual machine IP address to forward the
	// static NAT traffic to (useful when the virtual machine has secondary
	// NICs or IP addresses). Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	VMGuestIP *string `json:"vmGuestIp,omitempty" tf:"vm_guest_ip,omitempty"`

	// The virtual machine ID to enable the
	// static NAT feature for. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	VirtualMachineID *string `json:"virtualMachineId,omitempty" tf:"virtual_machine_id,omitempty"`
}

// NATSpec defines the desired state of NAT
type NATSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NATParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NATInitParameters `json:"initProvider,omitempty"`
}

// NATStatus defines the observed state of NAT.
type NATStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NATObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NAT is the Schema for the NATs API. Enables static NAT for a given IP address.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudstack}
type NAT struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipAddressId) || (has(self.initProvider) && has(self.initProvider.ipAddressId))",message="spec.forProvider.ipAddressId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.virtualMachineId) || (has(self.initProvider) && has(self.initProvider.virtualMachineId))",message="spec.forProvider.virtualMachineId is a required parameter"
	Spec   NATSpec   `json:"spec"`
	Status NATStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NATList contains a list of NATs
type NATList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NAT `json:"items"`
}

// Repository type metadata.
var (
	NAT_Kind             = "NAT"
	NAT_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NAT_Kind}.String()
	NAT_KindAPIVersion   = NAT_Kind + "." + CRDGroupVersion.String()
	NAT_GroupVersionKind = CRDGroupVersion.WithKind(NAT_Kind)
)

func init() {
	SchemeBuilder.Register(&NAT{}, &NATList{})
}
