// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/terasky-oss/provider-cloudstack/apis/machines/v1alpha1"
	v1alpha1network "github.com/terasky-oss/provider-cloudstack/apis/network/v1alpha1"
	v1alpha1security "github.com/terasky-oss/provider-cloudstack/apis/security/v1alpha1"
	v1alpha1storage "github.com/terasky-oss/provider-cloudstack/apis/storage/v1alpha1"
	v1alpha1system "github.com/terasky-oss/provider-cloudstack/apis/system/v1alpha1"
	v1alpha1apis "github.com/terasky-oss/provider-cloudstack/apis/v1alpha1"
	v1beta1 "github.com/terasky-oss/provider-cloudstack/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1security.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1system.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
